# Generated by Django 4.1.7 on 2023-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employeeexperience_employeeeducation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeexperience",
            name="company1salary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeexperience",
            name="company2salary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeexperience",
            name="company3salary",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
